---
- name: test playbook
  hosts: all
  gather_facts: yes
  remote_user: ubuntu
  tasks:

    - name: ensure nano is installed
      become: yes
      ansible.builtin.apt:
        name: nano
        state: present
    
    - name: print nano version
      ansible.builtin.command: nano --version
      register: nano_version
    
    - name: print nano version
      debug:
        var: nano_version.stdout
    
    - name: create user for trace
      become: yes
      ansible.builtin.user:
        name: trace
        state: present
        system: false
        groups: sudo
        append: yes
        password: $6$trace123$GIILptnD7gvJOfJzTkA6aMEdNF0s8gwO9IPchTX8CenHtNai8T/ageGdmXsj2aYX1PDckjUiNwXnEuEYc75/H/
    
    - name: create .ssh directory for trace
      ansible.builtin.file:
        path: /home/trace/.ssh
        state: directory
        owner: trace
        group: trace
        mode: '0700'
      become: yes
    
    - name: copy authorized_keys from ubuntu to trace
      ansible.builtin.copy:
        src: /home/ubuntu/.ssh/authorized_keys
        dest: /home/trace/.ssh/authorized_keys
        owner: trace
        group: trace
        mode: '0600'
        remote_src: yes
      become: yes