name: Terraform Format

on:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Run terraform fmt
        id: fmt
        run: |
          if terraform fmt -recursive -check; then
            echo "No formatting changes needed."
          else
            terraform fmt -recursive
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git checkout -b terraform-fmt-fix
            git add .
            git commit -m "Automatic terraform fmt fixes"
            git push --set-upstream origin terraform-fmt-fix
            echo "::set-output name=need-pr::true"
          fi

      - name: Create Pull Request
        if: steps.fmt.outputs.need-pr == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatic terraform fmt fixes"
          title: "Automatic terraform fmt fixes"
          body: "This pull request contains automatic formatting fixes by terraform fmt."
          branch: terraform-fmt-fix
          base: main
